language: python
sudo: false
dist: trusty
cache: yarn
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
- conda config --remove channels defaults
- conda config --add channels conda-forge
- conda update -q conda
- conda info -a
- conda install nodejs notebook
- which pip
- pip --version
- pip install --pre jupyterlab
script:
- yarn
- yarn run build
- jupyter labextension link packages/fasta-extension --no-build
- jupyter labextension link packages/geojson-extension --no-build
- jupyter labextension link packages/katex-extension --no-build
- jupyter labextension link packages/plotly-extension --no-build
- jupyter labextension link packages/vega2-extension --no-build
- jupyter labextension link packages/vega3-extension --no-build
- jupyter labextension link packages/vega4-extension --no-build
- jupyter labextension link packages/mathjax3-extension --no-build
- NODE_OPTIONS=--max-old-space-size=16000 jupyter lab build
- python -m jupyterlab.browser_check
